[package]
name = "wrun"
version = "0.2.0"
edition = "2021"
description = "A CLI runner for Wren scripts with system integration"
license = "MIT"

[dependencies]
# ruwren = { path = "../ruwren" }
ruwren = "0.4.10"
clap = { version = "4", features = ["derive"] }
